@extends('base')

@section('maincontent')
    <div id="contTablaIzq">
        <div id="p-container" class="container px-lg-8.5 px-md-5">
            <div class="row mb-4">
                <div class="col-12 col-sm-12">
                    <br>
                    <h1><strong>ESTADÍSTICAS</strong></h1>
                </div>
            </div>

            <hr>
            <br>
            <div class="col-12 col-sm-12 my-4">
                <p> <strong> Cohorte generacional Maestría</strong></p>
            </div>

            <div class="accordion p-2" id="accordionExample">
                <div class="accordion-item">
                    <div class="accordion-item">
                        <h2 class="accordion-header" id="headingThree">
                            <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse"
                                data-bs-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
                                <strong>Global &nbsp</strong> <i class="fa-solid fa-arrow-down-long"></i>
                            </button>
                        </h2>
                        <div id="collapseThree" class="accordion-collapse collapse" aria-labelledby="headingThree"
                            data-bs-parent="#accordionExample">
                            <div class="accordion-body">
                                <div class="accordion-body" id="accordionTextM">
                                    <table class="width200">
                                        <thead>
                                            <tr>
                                                <th id="tablaTitulos"><b>Generación</b></th>
                                                <th id="tablaTitulos"><b>Ingresos</b></th>
                                                <th id="tablaTitulos"><b>Graduados</b></th>
                                                <th id="tablaTitulos"><b>% de Graduados/Ingresos</b></th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <tr>
                                                <td>2002-08</td>
                                                <td>6</td>
                                                <td>4</td>
                                                <td>66.7</td>
                                            </tr>
                                            <tr>
                                                <td>2003-08</td>
                                                <td>13</td>
                                                <td>11</td>
                                                <td>84.6</td>
                                            </tr>
                                            <tr>
                                                <td>2004-08</td>
                                                <td>17</td>
                                                <td>15</td>
                                                <td>88.2</td>
                                            </tr>
                                            <tr>
                                                <td>2005-08</td>
                                                <td>14</td>
                                                <td>12</td>
                                                <td>85.7</td>
                                            </tr>
                                            <tr>
                                                <td>2006-08</td>
                                                <td>23</td>
                                                <td>14</td>
                                                <td>60.9</td>
                                            </tr>
                                            <tr>
                                                <td>2007-08</td>
                                                <td>17</td>
                                                <td>13</td>
                                                <td>76.5</td>
                                            </tr>
                                            <tr>
                                                <td>2008-08</td>
                                                <td>32</td>
                                                <td>27</td>
                                                <td>84.4</td>
                                            </tr>
                                            <tr>
                                                <td>2009-08</td>
                                                <td>48</td>
                                                <td>43</td>
                                                <td>89.6</td>
                                            </tr>
                                            <tr>
                                                <td>2010-08</td>
                                                <td>50</td>
                                                <td>44</td>
                                                <td>88.0</td>
                                            </tr>
                                            <tr>
                                                <td>2011-08</td>
                                                <td>38</td>
                                                <td>32</td>
                                                <td>84.2</td>
                                            </tr>
                                            <tr>
                                                <td>2012-08</td>
                                                <td>40</td>
                                                <td>37</td>
                                                <td>92.5</td>
                                            </tr>
                                            <tr>
                                                <td>2013-08</td>
                                                <td>33</td>
                                                <td>31</td>
                                                <td>93.9</td>
                                            </tr>
                                            <tr>
                                                <td>2014-08</td>
                                                <td>34</td>
                                                <td>30</td>
                                                <td>88.2</td>
                                            </tr>
                                            <tr>
                                                <td>2015-08</td>
                                                <td>17</td>
                                                <td>17</td>
                                                <td>100.0</td>
                                            </tr>
                                            <tr>
                                                <td>2016-08</td>
                                                <td>40</td>
                                                <td>34</td>
                                                <td>85.0</td>
                                            </tr>
                                            <tr>
                                                <td>2017-08</td>
                                                <td>24</td>
                                                <td>22</td>
                                                <td>91.7</td>
                                            </tr>
                                            <tr>
                                                <td>2018-08</td>
                                                <td>31</td>
                                                <td>30</td>
                                                <td>96.8</td>
                                            </tr>
                                            <tr>
                                                <td>2019-08</td>
                                                <td>23</td>
                                                <td>17</td>
                                                <td>73.9</td>
                                            </tr>
                                            <tr>
                                                <td>2020-08</td>
                                                <td>36</td>
                                                <td>0</td>
                                                <td>0</td>
                                            </tr>
                                            <tr>
                                                <td>2021-08</td>
                                                <td>22</td>
                                                <td>0</td>
                                                <td>0</td>
                                            </tr>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="accordion-item">
                        <h2 class="accordion-header" id="headingTwo">
                            <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse"
                                data-bs-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                                <strong>Becarios CONACyT &nbsp</strong> <i class="fa-solid fa-arrow-down-long"></i>
                            </button>
                        </h2>
                        <div id="collapseTwo" class="accordion-collapse collapse" aria-labelledby="headingTwo"
                            data-bs-parent="#accordionExample">
                            <div class="accordion-body">

                                <table class="width200">
                                    <thead>
                                        <tr>
                                            <th><b id="tablaTitulos">Generación</b></th>
                                            <th><b id="tablaTitulos">Ingresos</b></th>
                                            <th><b id="tablaTitulos">Graduados</b></th>
                                            <th><b id="tablaTitulos">% Graduados/Ingresos</b></th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <tr>

                                            <td>2002-08</td>
                                            <td>4</td>
                                            <td>4</td>
                                            <td>100</td>
                                        </tr>
                                        <tr>
                                            <td>2003-08</td>
                                            <td>13</td>
                                            <td>11</td>
                                            <td>84.6</td>
                                        </tr>
                                        <tr>
                                            <td>2004-08</td>
                                            <td>16</td>
                                            <td>15</td>
                                            <td>93.8</td>
                                        </tr>
                                        <tr>
                                            <td>2005-08</td>
                                            <td>13</td>
                                            <td>12</td>
                                            <td>92.3</td>
                                        </tr>
                                        <tr>
                                            <td>2006-08</td>
                                            <td>18</td>
                                            <td>14</td>
                                            <td>77.8</td>
                                        </tr>
                                        <tr>
                                            <td>2007-08</td>
                                            <td>16</td>
                                            <td>13</td>
                                            <td>81.3</td>
                                        </tr>
                                        <tr>
                                            <td>2008-08</td>
                                            <td>32</td>
                                            <td>27</td>
                                            <td>84.4</td>
                                        </tr>
                                        <tr>
                                            <td>2009-08</td>
                                            <td>48</td>
                                            <td>43</td>
                                            <td>89.6</td>
                                        </tr>
                                        <tr>
                                            <td>2010-08</td>
                                            <td>50</td>
                                            <td>44</td>
                                            <td>88.0</td>
                                        </tr>
                                        <tr>
                                            <td>2011-08</td>
                                            <td>36</td>
                                            <td>30</td>
                                            <td>83.3</td>
                                        </tr>
                                        <tr>
                                            <td>2012-08</td>
                                            <td>40</td>
                                            <td>37</td>
                                            <td>92.5</td>
                                        </tr>
                                        <tr>
                                            <td>2013-08</td>
                                            <td>33</td>
                                            <td>31</td>
                                            <td>93.9</td>
                                        </tr>
                                        <tr>
                                            <td>2014-08</td>
                                            <td>34</td>
                                            <td>30</td>
                                            <td>88.2</td>
                                        </tr>
                                        <tr>
                                            <td>2015-08</td>
                                            <td>17</td>
                                            <td>17</td>
                                            <td>100</td>
                                        </tr>
                                        <tr>
                                            <td>2016-08</td>
                                            <td>40</td>
                                            <td>29</td>
                                            <td>72.5</td>
                                        </tr>
                                        <tr>
                                            <td>2017-08</td>
                                            <td>24</td>
                                            <td>16</td>
                                            <td>66.7</td>
                                        </tr>
                                        <tr>
                                            <td>2018-08</td>
                                            <td>31</td>
                                            <td>22</td>
                                            <td>71.0</td>
                                        </tr>
                                        <tr>
                                            <td>2019-08</td>
                                            <td>23</td>
                                            <td>12</td>
                                            <td>52.2</td>
                                        </tr>
                                        <tr>
                                            <td>2020-08</td>
                                            <td>36</td>
                                            <td>0</td>
                                            <td>0</td>
                                        </tr>
                                        <tr>
                                            <td>2021-08</td>
                                            <td>22</td>
                                            <td>0</td>
                                            <td>0</td>
                                        </tr>
                                    </tbody>
                                </table>
                                </main>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <br>
            <div class="col-12 col-sm-12 my-4">
                <p><strong>Cohorte generacional Doctorado</strong></p>
            </div>
            <div class="accordion p-2" id="accordionExample">
                <div class="accordion-item">
                    <div class="accordion-item">
                        <h2 class="accordion-header" id="headingFour">
                            <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse"
                                data-bs-target="#collapseFour" aria-expanded="false" aria-controls="collapseFour">
                                <strong>Global &nbsp</strong> <i class="fa-solid fa-arrow-down-long"></i>
                            </button>
                        </h2>
                        <div id="collapseFour" class="accordion-collapse collapse" aria-labelledby="headingFour"
                            data-bs-parent="#accordionExample">
                            <div class="accordion-body">
                                <table class="width200">
                                    <thead>
                                        <tr>
                                            <th id="tablaTitulos"><b>Generación</b></th>
                                            <th id="tablaTitulos"><b>Ingresos</b></th>
                                            <th id="tablaTitulos"><b>Graduados</b></th>
                                            <th id="tablaTitulos"><b>% de Graduados/Ingresos</b></th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <tr>
                                            <td>2002-08</td>
                                            <td>6</td>
                                            <td>4</td>
                                            <td>66.7</td>
                                        </tr>
                                        <tr>
                                            <td>2003-02</td>
                                            <td>6</td>
                                            <td>3</td>
                                            <td>50.0</td>
                                        </tr>
                                        <tr>
                                            <td>2003-08</td>
                                            <td>4</td>
                                            <td>2</td>
                                            <td>50.0</td>
                                        </tr>
                                        <tr>
                                            <td>2004-02</td>
                                            <td>1</td>
                                            <td>1</td>
                                            <td>100.0</td>
                                        </tr>
                                        <tr>
                                            <td>2004-08</td>
                                            <td>8</td>
                                            <td>7</td>
                                            <td>87.5</td>
                                        </tr>
                                        <tr>
                                            <td>2005-02</td>
                                            <td>2</td>
                                            <td>2</td>
                                            <td>100.0</td>
                                        </tr>
                                        <tr>
                                            <td>2005-08</td>
                                            <td>11</td>
                                            <td>7</td>
                                            <td>63.6</td>
                                        </tr>
                                        <tr>
                                            <td>2006-02</td>
                                            <td>5</td>
                                            <td>4</td>
                                            <td>80.0</td>
                                        </tr>
                                        <tr>
                                            <td>2006-08</td>
                                            <td>4</td>
                                            <td>4</td>
                                            <td>80.0</td>
                                        </tr>
                                        <tr>
                                            <td>2007-08</td>
                                            <td>6</td>
                                            <td>4</td>
                                            <td>66.7</td>
                                        </tr>
                                        <tr>
                                            <td>2008-02</td>
                                            <td>1</td>
                                            <td>1</td>
                                            <td>100.0</td>
                                        </tr>
                                        <tr>
                                            <td>2008-08</td>
                                            <td>6</td>
                                            <td>3</td>
                                            <td>50.0</td>
                                        </tr>
                                        <tr>
                                            <td>2009-02</td>
                                            <td>4</td>
                                            <td>2</td>
                                            <td>50.0</td>
                                        </tr>
                                        <tr>
                                            <td>2009-08</td>
                                            <td>3</td>
                                            <td>2</td>
                                            <td>66.7</td>
                                        </tr>
                                        <tr>
                                            <td>2010-02</td>
                                            <td>5</td>
                                            <td>2</td>
                                            <td>40.0</td>
                                        </tr>
                                        <tr>
                                            <td>2010-08</td>
                                            <td>6</td>
                                            <td>5</td>
                                            <td>83.3</td>
                                        </tr>
                                        <tr>
                                            <td>2011-02</td>
                                            <td>3</td>
                                            <td>3</td>
                                            <td>100.0</td>
                                        </tr>
                                        <tr>
                                            <td>2011-08</td>
                                            <td>4</td>
                                            <td>4</td>
                                            <td>100.0</td>
                                        </tr>
                                        <tr>
                                            <td>2012-02</td>
                                            <td>8</td>
                                            <td>8</td>
                                            <td>100.0</td>
                                        </tr>
                                        <tr>
                                            <td>2012-08</td>
                                            <td>10</td>
                                            <td>8</td>
                                            <td>80.0</td>
                                        </tr>
                                        <tr>
                                            <td>2013-02</td>
                                            <td>9</td>
                                            <td>6</td>
                                            <td>66.7</td>
                                        </tr>
                                        <tr>
                                            <td>2013-08</td>
                                            <td>3</td>
                                            <td>3</td>
                                            <td>100.0</td>
                                        </tr>
                                        <tr>
                                            <td>2014-02</td>
                                            <td>4</td>
                                            <td>2</td>
                                            <td>50.0</td>
                                        </tr>
                                        <tr>
                                            <td>2015-02</td>
                                            <td>9</td>
                                            <td>8</td>
                                            <td>88.9</td>
                                        </tr>
                                        <tr>
                                            <td>2016-02</td>
                                            <td>9</td>
                                            <td>7</td>
                                            <td>77.8</td>
                                        </tr>
                                        <tr>
                                            <td>2017-02</td>
                                            <td>10</td>
                                            <td>4</td>
                                            <td>40.0</td>
                                        </tr>
                                        <tr>
                                            <td>2018-02</td>
                                            <td>5</td>
                                            <td>2</td>
                                            <td>40.0</td>
                                        </tr>
                                        <tr>
                                            <td>2019-02</td>
                                            <td>9</td>
                                            <td>0</td>
                                            <td>0</td>
                                        </tr>
                                        <tr>
                                            <td>2020-02</td>
                                            <td>9</td>
                                            <td>0</td>
                                            <td>0</td>
                                        </tr>
                                        <tr>
                                            <td>2021-02</td>
                                            <td>3</td>
                                            <td>0</td>
                                            <td>0</td>
                                        </tr>
                                        <tr>
                                            <td>2021-08</td>
                                            <td>4</td>
                                            <td>0</td>
                                            <td>0</td>
                                        </tr>
                                        <tr>
                                            <td>2022-02</td>
                                            <td>4</td>
                                            <td>0</td>
                                            <td>0</td>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                    <div class="accordion-item">
                        <h2 class="accordion-header" id="headingFive">
                            <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse"
                                data-bs-target="#collapseFive" aria-expanded="false" aria-controls="collapseFive">
                                <strong>Becarios CONACyT &nbsp</strong> <i class="fa-solid fa-arrow-down-long"></i>
                            </button>
                        </h2>
                        <div id="collapseFive" class="accordion-collapse collapse" aria-labelledby="headingFive"
                            data-bs-parent="#accordionExample">
                            <div class="accordion-body">
                                <table class="width200">
                                    <thead>
                                        <tr>
                                            <th id="tablaTitulos"><b>Generación</b></th>
                                            <th id="tablaTitulos"><b>Ingresos</b></th>
                                            <th id="tablaTitulos"><b>Graduados</b></th>
                                            <th id="tablaTitulos"><b>% de Graduados/Ingresos</b></th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <tr>
                                            <td>2002-08</td>
                                            <td>2</td>
                                            <td>2</td>
                                            <td>100.0</td>
                                        </tr>
                                        <tr>
                                            <td>2003-02</td>
                                            <td>4</td>
                                            <td>3</td>
                                            <td>75.0</td>
                                        </tr>
                                        <tr>
                                            <td>2003-08</td>
                                            <td>2</td>
                                            <td>1</td>
                                            <td>50.0</td>
                                        </tr>
                                        <tr>
                                            <td>2004-02</td>
                                            <td>1</td>
                                            <td>1</td>
                                            <td>100.0</td>
                                        </tr>
                                        <tr>
                                            <td>2004-08</td>
                                            <td>5</td>
                                            <td>5</td>
                                            <td>100.0</td>
                                        </tr>
                                        <tr>
                                            <td>2005-02</td>
                                            <td>2</td>
                                            <td>2</td>
                                            <td>100.0</td>
                                        </tr>
                                        <tr>
                                            <td>2005-08</td>
                                            <td>9</td>
                                            <td>7</td>
                                            <td>77.8</td>
                                        </tr>
                                        <tr>
                                            <td>2006-02</td>
                                            <td>5</td>
                                            <td>4</td>
                                            <td>80.0</td>
                                        </tr>
                                        <tr>
                                            <td>2006-08</td>
                                            <td>5</td>
                                            <td>4</td>
                                            <td>80.0</td>
                                        </tr>
                                        <tr>
                                            <td>2007-08</td>
                                            <td>6</td>
                                            <td>4</td>
                                            <td>66.7</td>
                                        </tr>
                                        <tr>
                                            <td>2008-02</td>
                                            <td>1</td>
                                            <td>1</td>
                                            <td>100.0</td>
                                        </tr>
                                        <tr>
                                            <td>2008-08</td>
                                            <td>6</td>
                                            <td>3</td>
                                            <td>50.0</td>
                                        </tr>
                                        <tr>
                                            <td>2009-02</td>
                                            <td>4</td>
                                            <td>2</td>
                                            <td>50.0</td>
                                        </tr>
                                        <tr>
                                            <td>2009-08</td>
                                            <td>3</td>
                                            <td>2</td>
                                            <td>66.7</td>
                                        </tr>
                                        <tr>
                                            <td>2010-02</td>
                                            <td>5</td>
                                            <td>2</td>
                                            <td>40.0</td>
                                        </tr>
                                        <tr>
                                            <td>2010-08</td>
                                            <td>6</td>
                                            <td>5</td>
                                            <td>83.3</td>
                                        </tr>
                                        <tr>
                                            <td>2011-02</td>
                                            <td>3</td>
                                            <td>3</td>
                                            <td>100.0</td>
                                        </tr>
                                        <tr>
                                            <td>2011-08</td>
                                            <td>4</td>
                                            <td>4</td>
                                            <td>100.0</td>
                                        </tr>
                                        <tr>
                                            <td>2012-02</td>
                                            <td>8</td>
                                            <td>8</td>
                                            <td>100.0</td>
                                        </tr>
                                        <tr>
                                            <td>2012-08</td>
                                            <td>10</td>
                                            <td>8</td>
                                            <td>80.0</td>
                                        </tr>
                                        <tr>
                                            <td>2013-02</td>
                                            <td>9</td>
                                            <td>6</td>
                                            <td>66.7</td>
                                        </tr>
                                        <tr>
                                            <td>2013-08</td>
                                            <td>3</td>
                                            <td>3</td>
                                            <td>100.0</td>
                                        </tr>
                                        <tr>
                                            <td>2014-02</td>
                                            <td>4</td>
                                            <td>2</td>
                                            <td>50.0</td>
                                        </tr>
                                        <tr>
                                            <td>2015-02</td>
                                            <td>9</td>
                                            <td>8</td>
                                            <td>88.9</td>
                                        </tr>
                                        <tr>
                                            <td>2016-02</td>
                                            <td>9</td>
                                            <td>7</td>
                                            <td>77.8</td>
                                        </tr>
                                        <tr>
                                            <td>2017-02</td>
                                            <td>10</td>
                                            <td>4</td>
                                            <td>40.0</td>
                                        </tr>
                                        <tr>
                                            <td>2018-02</td>
                                            <td>5</td>
                                            <td>2</td>
                                            <td>40.0</td>
                                        </tr>
                                        <tr>
                                            <td>2019-02</td>
                                            <td>9</td>
                                            <td>0</td>
                                            <td>0</td>
                                        </tr>
                                        <tr>
                                            <td>2020-02</td>
                                            <td>9</td>
                                            <td>0</td>
                                            <td>0</td>
                                        </tr>
                                        <tr>
                                            <td>2021-02</td>
                                            <td>3</td>
                                            <td>0</td>
                                            <td>0</td>
                                        </tr>
                                        <tr>
                                            <td>2021-08</td>
                                            <td>4</td>
                                            <td>0</td>
                                            <td>0</td>
                                        </tr>
                                        <tr>
                                            <td>2022-02</td>
                                            <td>4</td>
                                            <td>0</td>
                                            <td>0</td>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <br><br>
        </div>
    </div>
@endsection
